[user]
name = "Alejandro Anzola"
email = "me@alejandroanzola.info"

[ui]
editor = "nvim"
default-command = "log"

[merge-tools.neovim]
diff-invocation-mode = "file-by-file"

[remotes.origin]
auto-track-bookmarks = "glob:aanzola/*"
